swagger: "2.0"
info:
  title: Student API
  version: "1.0"

paths:
  /students:
    get:
      operationId: students.get_all_students
      responses:
        200:
          description: OK

    post:
      operationId: students.add_student
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              course:
                type: string
      responses:
        201:
          description: Created

  /students/{id}:
    put:
      operationId: students.update_student
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - in: body
          name: body
          schema:
            type: object
      responses:
        200:
          description: Updated

    delete:
      operationId: students.delete_student
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Deleted
